class mHTMLclass:
    mDocType = '<!doctype html>'
    mOpenHTML = '<html lang="en">'
    mCloseHTML = '</html>'
    mOpenHead = '<head>'
    mCloseHead = '</head>'
    mMeta = '<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">'
    mLinkCSS = '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">'
    mOpenTitle = '<title>'
    mCloseTitle = '</title>'
    mOpenBody = '<body>'
    mCloseBody = '</body>'
    mOpenHeadings1 = '<h1>'
    mCloseHeadings1 = '</h1>'
    mLinkJS = '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>'
    mContainer = '<div class="container">'
    mCloseDiv = '</div>'
    mRow = '<div class="row">'
    mCol = '<div class="col">'